### ISSUE TITLE
looping on dumping LLB

### ISSUE THREAD

**Issue by johnnynoone** [iH8sn0w/iFaith#1]
I'm using an iPhone 3GS with IOS 4.2.1 and iFaith v1.3.2

I'm trying to use the Dump SHSH Blobs feature but it is stuck at LLB. It keeps looping this:
Dumping... [Please Wait]
10/13 SHSH Blobs Captured Pass # 0/5
10/13 SHSH Blobs Captured Pass # 1/5
10/13 SHSH Blobs Captured Pass # 2/5
10/13 SHSH Blobs Captured Pass # 3/5
10/13 SHSH Blobs Captured Pass # 4/5
10/13 SHSH Blobs Captured Pass # 5/5
Verifying Blob...

**Comment by themrzmaster** [comment]
this ifaith is outdate
